package net.rlviana.pricegrabber.ws.service.site;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.rlviana.pricegrabber.domain.entity.core.Site;
import net.rlviana.pricegrabber.domain.response.core.SiteFindResponse;
import net.rlviana.pricegrabber.domain.response.core.SiteResponse;
import net.rlviana.pricegrabber.domain.search.core.SiteSearchCriteria;
import net.rlviana.pricegrabber.ws.service.exception.ServiceException;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SitePortType", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SitePortType {

  /**
   * 
   * @param criteria
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteFindResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/listSites")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "listSites", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.ListSites")
  @ResponseWrapper(localName = "listSitesResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.ListSitesResponse")
  public
      SiteFindResponse
      listSites(
          @WebParam(name = "criteria", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") SiteSearchCriteria criteria) throws ServiceException;

  /**
   * 
   * @param siteId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/deleteSite")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "deleteSite", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.DeleteSite")
  @ResponseWrapper(localName = "deleteSiteResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.DeleteSiteResponse")
  public
      SiteResponse
      deleteSite(
          @WebParam(name = "siteId", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") Long siteId) throws ServiceException;

  /**
   * 
   * @param criteria
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteFindResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/searchSites")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "searchSites", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.SearchSites")
  @ResponseWrapper(localName = "searchSitesResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.SearchSitesResponse")
  public
      SiteFindResponse
      searchSites(
          @WebParam(name = "criteria", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") SiteSearchCriteria criteria) throws ServiceException;

  /**
   * 
   * @param site
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/createSite")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "createSite", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.CreateSite")
  @ResponseWrapper(localName = "createSiteResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.CreateSiteResponse")
  public
      SiteResponse
      createSite(
          @WebParam(name = "site", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") Site site) throws ServiceException;

  /**
   * 
   * @param site
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/updateSite")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "updateSite", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.UpdateSite")
  @ResponseWrapper(localName = "updateSiteResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.UpdateSiteResponse")
  public
      SiteResponse
      updateSite(
          @WebParam(name = "site", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") Site site) throws ServiceException;

  /**
   * 
   * @param siteId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/site/findSiteById")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site")
  @RequestWrapper(localName = "findSiteById", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.FindSiteById")
  @ResponseWrapper(localName = "findSiteByIdResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site",
      className = "net.rlviana.pricegrabber.ws.service.site.FindSiteByIdResponse")
  public
      SiteResponse
      findSiteById(
          @WebParam(name = "siteId", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/site") Long siteId) throws ServiceException;

}
