package net.rlviana.pricegrabber.ws.service.promotion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.rlviana.pricegrabber.domain.entity.core.Promotion;
import net.rlviana.pricegrabber.domain.response.core.PromotionFindResponse;
import net.rlviana.pricegrabber.domain.response.core.PromotionResponse;
import net.rlviana.pricegrabber.domain.search.core.PromotionSearchCriteria;
import net.rlviana.pricegrabber.ws.service.exception.ServiceException;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PromotionPortType", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PromotionPortType {

  /**
   * 
   * @param criteria
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionFindResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/listPromotions")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "listPromotions",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.ListPromotions")
  @ResponseWrapper(localName = "listPromotionsResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.ListPromotionsResponse")
  public
      PromotionFindResponse
      listPromotions(
          @WebParam(name = "criteria", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") PromotionSearchCriteria criteria) throws ServiceException;

  /**
   * 
   * @param promotionId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/deletePromotion")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "deletePromotion",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.DeletePromotion")
  @ResponseWrapper(localName = "deletePromotionResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.DeletePromotionResponse")
  public
      PromotionResponse
      deletePromotion(
          @WebParam(name = "promotionId", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") Long promotionId) throws ServiceException;

  /**
   * 
   * @param criteria
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionFindResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/searchPromotions")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "searchPromotions",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.SearchPromotions")
  @ResponseWrapper(localName = "searchPromotionsResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.SearchPromotionsResponse")
  public
      PromotionFindResponse
      searchPromotions(
          @WebParam(name = "criteria", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") PromotionSearchCriteria criteria) throws ServiceException;

  /**
   * 
   * @param promotion
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/createPromotion")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "createPromotion",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.CreatePromotion")
  @ResponseWrapper(localName = "createPromotionResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.CreatePromotionResponse")
  public
      PromotionResponse
      createPromotion(
          @WebParam(name = "promotion", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") Promotion promotion) throws ServiceException;

  /**
   * 
   * @param promotion
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/updatePromotion")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "updatePromotion",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.UpdatePromotion")
  @ResponseWrapper(localName = "updatePromotionResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.UpdatePromotionResponse")
  public
      PromotionResponse
      updatePromotion(
          @WebParam(name = "promotion", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") Promotion promotion) throws ServiceException;

  /**
   * 
   * @param promotionId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.PromotionResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/promotion/findPromotionById")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion")
  @RequestWrapper(localName = "findPromotionById",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.FindPromotionById")
  @ResponseWrapper(localName = "findPromotionByIdResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion",
      className = "net.rlviana.pricegrabber.ws.service.promotion.FindPromotionByIdResponse")
  public
      PromotionResponse
      findPromotionById(
          @WebParam(name = "promotionId", targetNamespace = "http://pricegrabber.rlviana.net/ws/service/promotion") Long promotionId) throws ServiceException;

}
