CREATE TABLE CO_COUNTRY (ID VARCHAR(2) NOT NULL, COD VARCHAR(255) NOT NULL, CODNUM VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE CO_LANGUAGE (ID VARCHAR(2) NOT NULL, COD VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE CO_CURRENCY (ID VARCHAR(2) NOT NULL, COD VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PG_ITEM (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(80), LOCKVERSION INTEGER, NAME VARCHAR(80) NOT NULL, PG_ITEMTYPE_ID INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PG_ITEMTYPE (ID INTEGER NOT NULL, DESCRIPTION VARCHAR(50), LOCKVERSION INTEGER, NAME VARCHAR(25) NOT NULL, PG_ITEMTYPE_ID INTEGER, PRIMARY KEY (ID))
CREATE TABLE PG_PROMOTION (ID BIGINT NOT NULL, ACTIVE SMALLINT DEFAULT 0, BEGINDATE TIMESTAMP, DESCRIPTION VARCHAR(80) NOT NULL, ENDDATE TIMESTAMP, LOCKVERSION INTEGER, NAME VARCHAR(80) NOT NULL, URL VARCHAR(50) NOT NULL, PG_SITE_ID BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PG_SITE (ID BIGINT NOT NULL, CREATEUSER VARCHAR(255), CREATED TIMESTAMP, DESCRIPTION VARCHAR(80) NOT NULL, LASTUPDATEUSER VARCHAR(255), LASTUPDATED TIMESTAMP, LOCKVERSION INTEGER, NAME VARCHAR(50) NOT NULL, URL VARCHAR(50) NOT NULL, CO_COUNTRY_ID VARCHAR(2) NOT NULL, CO_CURRENCY_ID VARCHAR(2) NOT NULL, CO_LANGUAGE_ID VARCHAR(2) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PG_SITEITEM (ID BIGINT NOT NULL, LOCKVERSION INTEGER, NAME VARCHAR(50) NOT NULL, SITECOD VARCHAR(20) NOT NULL, URL VARCHAR(50) NOT NULL, PG_ITEM_ID BIGINT, PG_SITE_ID BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PG_SITEITEMDATUM (ID BIGINT NOT NULL, AVAILABILITY VARCHAR(255), LOCKVERSION INTEGER, PRICEDATE TIMESTAMP, PRICETYPE INTEGER, PRICEVALUE DECIMAL(15), CO_CURRENCY_ID VARCHAR(2) NOT NULL, PG_SITEITEM_ID BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PG_PROMOTION_SITEITEM (PG_PROMOTION_ID BIGINT NOT NULL, PG_SITEITEM_ID BIGINT NOT NULL, PRIMARY KEY (PG_PROMOTION_ID, PG_SITEITEM_ID))
ALTER TABLE CO_COUNTRY ADD CONSTRAINT UNQ_CO_COUNTRY_0 UNIQUE (COD, CODNUM)
ALTER TABLE CO_LANGUAGE ADD CONSTRAINT UNQ_CO_LANGUAGE_0 UNIQUE (COD)
ALTER TABLE CO_CURRENCY ADD CONSTRAINT UNQ_CO_CURRENCY_0 UNIQUE (COD)
ALTER TABLE PG_ITEM ADD CONSTRAINT PGITEMPGITEMTYPEID FOREIGN KEY (PG_ITEMTYPE_ID) REFERENCES PG_ITEMTYPE (ID)
ALTER TABLE PG_ITEMTYPE ADD CONSTRAINT PGTMTYPEPGTMTYPEID FOREIGN KEY (PG_ITEMTYPE_ID) REFERENCES PG_ITEMTYPE (ID)
ALTER TABLE PG_PROMOTION ADD CONSTRAINT PGPROMOTIONPGSTEID FOREIGN KEY (PG_SITE_ID) REFERENCES PG_SITE (ID)
ALTER TABLE PG_SITE ADD CONSTRAINT PGSITECOLANGUAGEID FOREIGN KEY (CO_LANGUAGE_ID) REFERENCES CO_LANGUAGE (ID)
ALTER TABLE PG_SITE ADD CONSTRAINT PGSITECOCOUNTRY_ID FOREIGN KEY (CO_COUNTRY_ID) REFERENCES CO_COUNTRY (ID)
ALTER TABLE PG_SITE ADD CONSTRAINT PGSITECOCURRENCYID FOREIGN KEY (CO_CURRENCY_ID) REFERENCES CO_CURRENCY (ID)
ALTER TABLE PG_SITEITEM ADD CONSTRAINT PGSITEITEMPGSITEID FOREIGN KEY (PG_SITE_ID) REFERENCES PG_SITE (ID)
ALTER TABLE PG_SITEITEM ADD CONSTRAINT PGSITEITEMPGITEMID FOREIGN KEY (PG_ITEM_ID) REFERENCES PG_ITEM (ID)
ALTER TABLE PG_SITEITEMDATUM ADD CONSTRAINT PGSTTMDTUMCCRRNCYD FOREIGN KEY (CO_CURRENCY_ID) REFERENCES CO_CURRENCY (ID)
ALTER TABLE PG_SITEITEMDATUM ADD CONSTRAINT PGSTTMDATUMPGSTTMD FOREIGN KEY (PG_SITEITEM_ID) REFERENCES PG_SITEITEM (ID)
ALTER TABLE PG_PROMOTION_SITEITEM ADD CONSTRAINT PGPRMTNSTTMPGSTTMD FOREIGN KEY (PG_SITEITEM_ID) REFERENCES PG_SITEITEM (ID)
ALTER TABLE PG_PROMOTION_SITEITEM ADD CONSTRAINT PGPRMTNSTTPGPRMTND FOREIGN KEY (PG_PROMOTION_ID) REFERENCES PG_PROMOTION (ID)
CREATE SEQUENCE PG_SITEITEM_SEQ START WITH 10
CREATE SEQUENCE PG_ITEMTYPE_SEQ START WITH 10
CREATE SEQUENCE PG_SITE_SEQ START WITH 10
CREATE SEQUENCE PG_PROMOTION_SEQ START WITH 10
CREATE SEQUENCE PG_SITEITEMDATUM_SEQ START WITH 10
CREATE SEQUENCE PG_ITEM_SEQ START WITH 10
