package net.rlviana.pricegrabber.ws.service.siteItemDatum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.rlviana.pricegrabber.domain.entity.core.SiteItemDatum;
import net.rlviana.pricegrabber.domain.response.core.SiteItemDatumResponse;
import net.rlviana.pricegrabber.ws.service.exception.ServiceException;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SiteItemDatumPortType",
    targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SiteItemDatumPortType {

  /**
   * 
   * @param parameters
   * @return
   *         returns net.rlviana.pricegrabber.ws.service.siteItemDatum.ListSiteItemDataResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/listSiteItemData")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
  @RequestWrapper(localName = "listSiteItemData",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.ListSiteItemData")
  @ResponseWrapper(localName = "listSiteItemDataResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.ListSiteItemDataResponse")
  public
      ListSiteItemDataResponse
      listSiteItemDatums(
          @WebParam(name = "listSiteItemData",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum", partName = "parameters") ListSiteItemData parameters) throws ServiceException;

  /**
   * 
   * @param siteItemDatumId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteItemDatumResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/deleteSiteItemDatum")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
  @RequestWrapper(localName = "deleteSiteItemDatum",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.DeleteSiteItemDatum")
  @ResponseWrapper(localName = "deleteSiteItemDatumResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.DeleteSiteItemDatumResponse")
  public
      SiteItemDatumResponse
      deleteSiteItemDatum(
          @WebParam(name = "siteItemDatumId",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum") Long siteItemDatumId) throws ServiceException;

  /**
   * 
   * @param parameters
   * @return
   *         returns net.rlviana.pricegrabber.ws.service.siteItemDatum.SearchSiteItemDataResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/searchSiteItemDatums")
  @WebResult(name = "searchSiteItemDataResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum", partName = "parameters")
  public
      SearchSiteItemDataResponse
      searchSiteItemDatums(
          @WebParam(name = "searchSiteItemData",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum", partName = "parameters") SearchSiteItemData parameters) throws ServiceException;

  /**
   * 
   * @param siteItemDatum
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteItemDatumResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/createSiteItemDatum")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
  @RequestWrapper(localName = "createSiteItemDatum",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.CreateSiteItemDatum")
  @ResponseWrapper(localName = "createSiteItemDatumResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.CreateSiteItemDatumResponse")
  public
      SiteItemDatumResponse
      createSiteItemDatum(
          @WebParam(name = "siteItemDatum",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum") SiteItemDatum siteItemDatum) throws ServiceException;

  /**
   * 
   * @param siteItemDatum
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteItemDatumResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/updateSiteItemDatum")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
  @RequestWrapper(localName = "updateSiteItemDatum",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.UpdateSiteItemDatum")
  @ResponseWrapper(localName = "updateSiteItemDatumResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.UpdateSiteItemDatumResponse")
  public
      SiteItemDatumResponse
      updateSiteItemDatum(
          @WebParam(name = "siteItemDatum",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum") SiteItemDatum siteItemDatum) throws ServiceException;

  /**
   * 
   * @param siteItemDatumId
   * @return
   *         returns net.rlviana.pricegrabber.domain.response.core.SiteItemDatumResponse
   */
  @WebMethod(action = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum/findSiteItemDatumById")
  @WebResult(targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum")
  @RequestWrapper(localName = "findSiteItemDatumById",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.FindSiteItemDatumById")
  @ResponseWrapper(localName = "findSiteItemDatumByIdResponse",
      targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum",
      className = "net.rlviana.pricegrabber.ws.service.siteItemDatum.FindSiteItemDatumByIdResponse")
  public
      SiteItemDatumResponse
      findSiteItemDatumById(
          @WebParam(name = "siteItemDatumId",
              targetNamespace = "http://pricegrabber.rlviana.net/ws/service/siteItemDatum") Long siteItemDatumId) throws ServiceException;

}
